-- liquibase formatted sql

-- changeset magamed:1
CREATE TABLE IF NOT EXISTS users
(
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(16) UNIQUE NOT NULL,
    EMAIL VARCHAR(25) UNIQUE NOT NULL,
    FULL_NAME VARCHAR(20) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL ,
    PASSWORD_HASH VARCHAR(16) NOT NULL,
    IS_BANNED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL
    );
-- changeset magamed:2
CREATE TABLE IF NOT EXISTS roles
(
    ID BIGSERIAL PRIMARY KEY,
    ROLE VARCHAR(10) UNIQUE NOT NULL
    );
-- changeset magamed:3
CREATE TABLE IF NOT EXISTS users_roles
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES roles(ID) ON DELETE CASCADE
    );

-- changeset magamed:4
CREATE TABLE IF NOT EXISTS authors
(
    ID BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR NOT NULL,
    BIRTHDATE DATE NOT NULL
);
-- changeset magamed:5
CREATE TABLE IF NOT EXISTS books
(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PRICE BIGINT NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES authors(ID)
    );