-- liquibase formatted sql

-- changeset magamed:1
CREATE TABLE IF NOT EXISTS users
(
    ID            BIGSERIAL PRIMARY KEY,
    USERNAME      VARCHAR(16) UNIQUE NOT NULL,
    EMAIL         VARCHAR(25) UNIQUE NOT NULL,
    FULL_NAME     VARCHAR(20)        NOT NULL,
    DATE_OF_BIRTH DATE               NOT NULL,
    PASSWORD_HASH VARCHAR(16)        NOT NULL,
    IS_BANNED     BOOLEAN   DEFAULT FALSE,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT    TIMESTAMP          NULL
);
-- changeset magamed:2
CREATE TABLE IF NOT EXISTS roles
(
    ID   BIGSERIAL PRIMARY KEY,
    ROLE VARCHAR(10) UNIQUE NOT NULL
);
-- changeset magamed:3
CREATE TABLE IF NOT EXISTS users_roles
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES roles (ID) ON DELETE CASCADE
);

-- changeset magamed:4
CREATE TABLE IF NOT EXISTS authors
(
    ID        BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR NOT NULL,
    BIRTHDATE DATE    NOT NULL
);
-- changeset magamed:5
CREATE TABLE IF NOT EXISTS books
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(50)  NOT NULL,
    PRICE       BIGINT       NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    AUTHOR_ID   BIGINT       NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES authors (ID)
);
--changeset magamed:6
CREATE TABLE IF NOT EXISTS categories
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(25) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR     NOT NULL
);
--changeset magamed:7
CREATE TABLE IF NOT EXISTS books_categories
(
    BOOK_ID     BIGINT NOT NULL,
    CATEGORY_ID BIGINT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES books (ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES categories (ID) ON DELETE CASCADE
);
--changeset magamed:8
DROP TABLE authors CASCADE;

--changeset magamed:9
ALTER TABLE books ADD column
AUTHOR VARCHAR;

--changeset magamed:10
ALTER TABLE books DROP COLUMN
AUTHOR_ID CASCADE;

--changeset magamed:11
ALTER TABLE books
ALTER COLUMN price TYPE DOUBLE PRECISION;

--changeset magamed:12
ALTER TABLE books
ADD COLUMN IF NOT EXISTS STOCK_QUANTITY BIGINT NOT NULL DEFAULT 0;

--changeset magamed:13
ALTER TABLE books
ADD COLUMN IF NOT EXISTS DELETED BOOLEAN NOT NULL DEFAULT FALSE;